config/routes.rb
Rails.application.routes.draw do
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :tasks, only: [:show, :edit, :destroy, :update]

    resources :task_lists, except: [:new] do
      resources :tasks, except: [:index, :edit, :show, :destroy, :update]
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'task_lists#new'
  end
# => Produce un loop:
#  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), via: [:get, :post]
  match '', to: redirect("/#{I18n.default_locale}"), via: [:get, :post]
end

app/models/task_list.rb
class TaskList < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :name, presence: true
  validates :slug, uniqueness: true

  extend FriendlyId
  friendly_id :name, use: :slugged

  # For not generate a new slug when name change
  # No generará un nuevo slug cuando el nombre cambie
  def should_generate_new_friendly_id?
     new_record?
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :set_task_list, only: [:show, :edit, :update, :destroy]
  after_action :destroy_from_cookie, only: [:destroy]
  before_action :list_ids, only: [:index, :new]
  after_action :save_in_cookie, only: [:create]

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  # GET /task_lists
  # GET /task_lists.json
  def index
    begin
    @task_lists = TaskList.find(list_ids)
    rescue ActiveRecord::RecordNotFound
      purge_invalid_cookies
  end
  end

  # GET /task_lists/1
  # GET /task_lists/1.json
  def show
  end

  # GET /task_lists/new
  def new
    @task_list = TaskList.new
    begin
    @last_list_tasks = TaskList.find(list_ids).last(5)
    rescue ActiveRecord::RecordNotFound
      purge_invalid_cookies
      retry
    end
  end

  # GET /task_lists/1/edit
  def edit
  end

  # POST /task_lists
  # POST /task_lists.json
  def create
    @task_list = TaskList.new(task_list_params)

    respond_to do |format|
      if @task_list.save
        format.html { redirect_to @task_list, notice: t('application.controller.task_list.create') }
        format.json { render :show, status: :created, location: @task_list }
      else
        format.html { render :new }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_lists/1
  # PATCH/PUT /task_lists/1.json
  def update
    respond_to do |format|
      if @task_list.update(task_list_params)
        format.html { redirect_to @task_list, notice: t('application.controller.task_list.update') }
        format.json { render :show, status: :ok, location: @task_list }
      else
        format.html { render :edit }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_lists/1
  # DELETE /task_lists/1.json
  def destroy
    @task_list.destroy
    respond_to do |format|
      format.html { redirect_to task_lists_url, notice: t('application.controller.task_list.destroy') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_list
      begin
        @task_list = TaskList.friendly.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to root_url, notice: t('application.controller.set_task_list')
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_list_params
      params.require(:task_list).permit(:name, :id)
    end

    def save_in_cookie
      cookies[@task_list.id] = @task_list.friendly_id if @task_list.persisted?
    end

    def destroy_from_cookie
      cookies.delete (@task_list.id) if @task_list.destroyed?
    end

    def list_ids
      a= cookies.select { |x| x[0].to_s.match(/^\d+$/) }
      Hash[a].keys
    end

    def record_not_found
     raise ActionController::RoutingError.new('Not Found')
    end

   def purge_invalid_cookies
     list_ids.each do |x|
       unless TaskList.exists?(id: x)
         cookies.delete(x)
       end
     end
   end
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/views/task_lists/_form.html.erb
<%= form_for(task_list, html: { class: 'form-horizontal' }) do |f| %>
  <% if task_list.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong><%= pluralize(task_list.errors.count, "error") %></strong> prohibited this task_list from being saved:
      <ul>
      <% task_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>


<% end %>


  <div class="center_text">
      <%= f.text_field :name , placeholder: t('task_list.new.placeholder'), class: "form-control input-lg", :required => true %>
  </div>
<br>
  <div class="actions center_text">
    <%= f.submit t('task_list.new.submit'), class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

<% unless @last_list_tasks.nil? ||  @last_list_tasks.empty? %>
<%= render 'last_list_tasks' %>
<% end %>

app/views/task_lists/_last_list_tasks.html.erb
<hr>
<br>
<div class="col-xl-5">
  <h4><%=t('task_list.new.latest')%></h4>
<div class="list-group">
  <% @last_list_tasks.each do |task_list| %>
  <a href= <%= task_list_url(task_list) %> class="list-group-item list-group-item-action">
      <%= task_list.name %>
      <span class="badge badge-pill badge-info float-right"><%= task_list.tasks.count %></span>
    </a>
  <% end %>
</div>
</div>

app/views/task_lists/_tasks.html.erb
<h4 style="float: left;">Tasks</h4>
<div class="table-responsive">
<table class="table table-striped table-sm ">
  <thead class="thead-inverse">
    <tr>
      <th><%= t 'task.description'%></th>
      <th class="center_text"><%= t 'task.status.status'%></th>
      <th class="center_text"><%= t 'task.priority.priority'%></th>
      <th class="center_text"><%= t 'task.type_of_task'%></th>
      <th class="center_text"><%= t 'task.completed'%></th>
      <th class="center_text"><%= t 'task.start_at'%></th>
      <th class="center_text"><%= t 'task.end_at'%></th>
      <th colspan="2" style="width: 5%;"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_list.tasks.sort.each do |task| %>
      <tr>
        <td><%= link_to task.description, task %></td>
        <td class="center_text"><%= t("task.status.#{task.status}") %></td>
        <td class="center_text"><%= t("task.priority.#{task.priority}") %></td>
        <td class="center_text"><%= t("task.type.#{task.type}") %></td>
        <td class="center_text"><%= "#{task.percentage_of_completion} %" if task.instance_of? LongTask %></td>
        <td class="center_text"><%= l task.start_at.to_date, format: :default if task.instance_of? TemporaryTask %></td>
        <td class="center_text"><%= l task.end_at.to_date, format: :default if task.instance_of? TemporaryTask %></td>
        <td><%= link_to t('application.edit'), edit_task_path(task, @task_list, locale: I18n.locale) %></td>
        <td><%= link_to t('application.delete'), task, method: :delete, data: { confirm: t('application.confirmation') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

app/views/task_lists/edit.html.erb
<br>
<h2 class="center_text"><%= t('task_list.editing')%></h2>
<%= render 'form', task_list: @task_list %>
<br>

<%= link_to t('application.show'), @task_list %> |
<%= link_to t('application.back'), task_lists_path %> |
<%= link_to t('application.delete'), @task_list, method: :delete, data: { confirm: t('application.confirmation') } %>

app/views/task_lists/index.html.erb
<% unless @task_lists.nil? or @task_lists.empty? %>
<h3><%= t('application.all_my_task_list')%>:</h3>

<div class="table-responsive">
<table class="table table-sm" >
  <thead class="thead-inverse">
    <tr>
      <th><%= t 'task_list.name'%></th>
      <th style="width: 10%;"><%= t 'task_list.created_at'%></th>
      <th style="width: 10%;"><%= t 'task_list.modified_at'%></th>
      <th class="center_text" style="width: 8%;"><%=t('task_list.tasks')%></th>
      <th colspan="2" style="width: 5%;"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_lists.each do |task_list| %>
      <tr>
        <td><%= link_to task_list.name, task_list %></td>
        <td><%= l task_list.created_at.getlocal.to_date, format: :short %></td>
        <td><%= l task_list.updated_at.getlocal.to_date, format: :short %></td>
        <td class="center_text"><%= task_list.tasks.count%></td>
        <td><%= link_to t('application.edit'), edit_task_list_path(task_list) %></td>
        <td><%= link_to t('application.delete'), task_list, method: :delete, data: { confirm: t('application.confirmation') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<% else %>
  <div class="alert alert-warning" role="alert">
    <strong><%= t('task_list.index.no_task_lists') %></strong> <%= t('task_list.index.no_task_lists_text') %> <%= t('task_list.new.tittle') %>
  </div>
<%end %>
<hr>
<%= link_to t('task_list.new.tittle'), root_url, class: 'btn btn-outline-primary' %>
<br>
<br>
<%= render 'layouts/notice' %>

app/views/task_lists/new.html.erb
<br>
<h2 class="center_text"><%= t 'task_list.new.tittle'%></h2>
<%= render 'form', task_list: @task_list %>
<br>
<%= render 'layouts/notice' %>

app/views/task_lists/show.html.erb
  <h3><strong><%= @task_list.name %></strong></h3>


<p>
<strong><%= t 'task_list.created_at'%>: </strong>
<%= l @task_list.created_at.getlocal, format: :short %>
 -
<strong><%= t 'task_list.modified_at'%>: </strong>
<%= l @task_list.updated_at.getlocal, format: :short %>
</p>
<%= link_to t('application.edit'), edit_task_list_path(@task_list) %> |
<%= link_to t('application.back'), task_lists_path %> |
<%= link_to t('application.delete'), @task_list, method: :delete, data: { confirm: t('application.confirmation') } %>

<hr>

<div style="float: right;">
<%= link_to t('application.new_task'), new_task_list_task_path(@task_list, @task, locale: I18n.locale), method: :get, class: 'btn btn-outline-primary'%>
</div>

<% if @task_list.tasks.empty? %>
<br><br>
  <div class="alert alert-success" role="alert">

  <strong><%=t('task_list.no_tasks')%></strong> <%=t('task_list.no_tasks_text')%> <%=t('application.new_task')%>
</div>
<% else %>
<%= render 'tasks' %>
<% end %>
<%= render 'layouts/notice' %>